#!/usr/bin/env python3
# Decode tools/gordon_art.txt (Unicode Braille art) into a 1-bpp bitmap
# and emit display/gordon_art.h for the kernel graphics splash.
#
# Each Braille cell (U+2800..U+28FF) packs a 2x4 dot grid:
#   bit0 -> (x0,y0)  bit3 -> (x1,y0)
#   bit1 -> (x0,y1)  bit4 -> (x1,y1)
#   bit2 -> (x0,y2)  bit5 -> (x1,y2)
#   bit6 -> (x0,y3)  bit7 -> (x1,y3)

import sys, os

ART = os.path.join(os.path.dirname(__file__), "gordon_art.txt")
OUT = os.path.join(os.path.dirname(__file__), "..", "display", "gordon_art.h")

# bit index -> (dx, dy) within the 2x4 cell
BITS = [(0,0),(0,1),(0,2),(1,0),(1,1),(1,2),(0,3),(1,3)]

def main():
    with open(ART, encoding="utf-8") as f:
        lines = [ln.rstrip("\n") for ln in f]
    # drop a possible trailing empty line
    while lines and lines[-1] == "":
        lines.pop()

    cols = max(len(ln) for ln in lines)
    W = cols * 2
    H = len(lines) * 4
    grid = [[0]*W for _ in range(H)]

    for cy, ln in enumerate(lines):
        for cx, ch in enumerate(ln):
            o = ord(ch)
            if 0x2800 <= o <= 0x28FF:
                bits = o - 0x2800
                for b,(dx,dy) in enumerate(BITS):
                    if bits & (1<<b):
                        grid[cy*4+dy][cx*2+dx] = 1
            # spaces / anything else -> blank

    # Trim fully-blank border rows/cols
    def row_blank(r): return all(v==0 for v in grid[r])
    def col_blank(c): return all(grid[r][c]==0 for r in range(len(grid)))

    top=0
    while top < len(grid) and row_blank(top): top+=1
    bot=len(grid)-1
    while bot>=0 and row_blank(bot): bot-=1
    left=0
    while left < W and col_blank(left): left+=1
    right=W-1
    while right>=0 and col_blank(right): right-=1

    grid = [row[left:right+1] for row in grid[top:bot+1]]
    H=len(grid); W=len(grid[0]) if grid else 0

    # Shrink-to-fit a 320x200 (mode 13h) screen, leaving a 1px margin.
    # OR-based area downscale: a destination pixel is lit if ANY source
    # pixel mapping to it is lit, so 1px line art never drops a stroke.
    MAXW, MAXH = 318, 198
    if W > MAXW or H > MAXH:
        import math
        scale = min(MAXW / W, MAXH / H)
        nW = max(1, int(W * scale))
        nH = max(1, int(H * scale))
        ng = [[0]*nW for _ in range(nH)]
        for dy in range(nH):
            sy0 = dy * H // nH
            sy1 = max(sy0+1, (dy+1) * H // nH)
            for dx in range(nW):
                sx0 = dx * W // nW
                sx1 = max(sx0+1, (dx+1) * W // nW)
                hit = 0
                for sy in range(sy0, sy1):
                    for sx in range(sx0, sx1):
                        if grid[sy][sx]:
                            hit = 1; break
                    if hit: break
                ng[dy][dx] = hit
        grid = ng
        H, W = nH, nW

    # ASCII preview to stderr
    sys.stderr.write("decoded %dx%d (after trim)\n" % (W,H))
    for row in grid:
        sys.stderr.write("".join('#' if v else ' ' for v in row) + "\n")

    # Pack 1bpp, MSB-first, each row padded to byte boundary
    stride = (W + 7)//8
    data = bytearray()
    for row in grid:
        for bx in range(stride):
            byte=0
            for bit in range(8):
                x=bx*8+bit
                if x<W and row[x]:
                    byte |= (0x80>>bit)
            data.append(byte)

    with open(OUT,"w") as f:
        f.write("// Auto-generated by tools/decode_gordon.py — do not edit.\n")
        f.write("// 1-bpp bitmap of the GordOS mascot, MSB-first, %d-byte rows.\n" % stride)
        f.write("#ifndef GORDON_ART_H\n#define GORDON_ART_H\n\n")
        f.write("#define GORDON_W %d\n" % W)
        f.write("#define GORDON_H %d\n" % H)
        f.write("#define GORDON_STRIDE %d\n\n" % stride)
        f.write("static const unsigned char gordon_bitmap[%d] = {\n" % len(data))
        for i in range(0,len(data),12):
            chunk=data[i:i+12]
            f.write("    " + ",".join("0x%02X"%b for b in chunk) + ",\n")
        f.write("};\n\n#endif\n")
    sys.stderr.write("wrote %s (%d bytes, stride %d)\n" % (OUT,len(data),stride))

if __name__=="__main__":
    main()
